import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    {
      type: 'category',
      label: 'General',
      link: {
        type: 'generated-index'
      },
      collapsed: false,
      items: [
        'README',
        'GLOBAL_STANDARDS',
      ],
    },
    {
      type: 'category',
      label: 'Robot Code Structure',
      link: {
        type: 'generated-index'
      },
      items: [
                'ROBOT_CODE_OVERVIEW',
        'ADVANTAGEKIT_STANDARDS',
        'SUBSYSTEM_STANDARDS',
        'COMMANDS_STANDARDS',
        'LOGGING_STANDARDS',
        'ROBOTSTATE_STANDARDS',
        'SUPERSTRUCTURE_STANDARDS'
      ],
    },
    'CONTROL_LOOP_STANDARDS',
    'LOGGING_STANDARDS',
    'ROBOTSTATE_STANDARDS',
    'CONSTANTS_STANDARDS',
    'GOMPEI_LIB_GEN',
    'SOTM'
  ],
};

export default sidebars;
